#!/bin/bash
# P.S.E.U.D.O.
# Platform SSO Enforcement (of) User Device Onboarding
# https://github.com/Macjutsu/pseudo
# by Kevin M. White

# The next line disables specific ShellCheck codes (https://github.com/koalaman/shellcheck) for the entire script.
# shellcheck disable=SC1003,SC2012,SC2024,SC2207

export PATH=/usr/bin:/bin:/usr/sbin:/sbin
PSEUDO_VERSION="1.0.0-beta5"
readonly PSEUDO_VERSION
PSEUDO_DATE="2026/04/28"
readonly PSEUDO_DATE
PSEUDO_USER_AGENT="pseudo/${PSEUDO_VERSION} $(curl --version | head -1 | sed -e 's/curl /curl\//')"
readonly PSEUDO_USER_AGENT

# MARK: *** Startup Workflow ***
################################################################################

# Set default parameters that are used throughout the script.
set_defaults() {
	# Optionally check for the installation of configuration profiles that would be required for the Platform SSO workflow.
	# The format is a comma-separated list of configuration profile identifiers (no spacing around commas and no comma required if only specifying a single item).
	# Configuration profile identifiers include display names, UUIDs, or any other matching text string.
	# A blank "" value will disable this optional validation.
	CHECK_REQUIRED_CONFIG_PROFILES=""
	readonly CHECK_REQUIRED_CONFIG_PROFILES
	
	# Optionally enable the Touch ID configuration workflow.
	# The supported values are "REQUIRED" or "OPTIONAL". Any other value, including blank "", will disable the Touch ID workflow:
	TOUCH_ID_CONFIG=""
	readonly TOUCH_ID_CONFIG
	
	# Optionally automatically enable Platform SSO related AutoFill extensions.
	# Any other value besides "TRUE" will disable this option.
	ENABLE_AUTOFILL_EXTENSIONS=""
	readonly ENABLE_AUTOFILL_EXTENSIONS
	
	# Optional mode that will always run the Platform SSO registration workflow even if the account was previously registered.
	# Any other value besides "TRUE" will disable this option.
	REPAIR_MODE=""
	readonly REPAIR_MODE
	
	# Optionally (after succesfull Platform SSO enrollment) update Jamf Pro device compliance and inventory.
	# Any other value besides "TRUE" will disable this option.
	UPDATE_JAMF_PRO=""
	readonly UPDATE_JAMF_PRO
	
	# Optionally (after succesfull Platform SSO enrollment) sync Workspace ONE.
	# Any other value besides "TRUE" will disable this option.
	UPDATE_WORKSPACE_ONE=""
	readonly UPDATE_WORKSPACE_ONE
	
	# Optionally (after succesfull Platform SSO enrollment) update Workspace ONE sensor(s).
	# The format is a comma-separated list of Workspace ONE sensor names to trigger (no spacing around commas and no comma required if only specifying a single item).
	# A blank "" value will disable this option.
	UPDATE_WORKSPACE_ONE_SENSORS=""
	readonly UPDATE_WORKSPACE_ONE_SENSORS
	
	# *** The remaining parameters are NOT OPTIONAL but can be modified to better fit your workflow. ***
	################################################################################
	
	# The name of your company or organization that appears in dialogs:
	DISPLAY_ORGANIZATION_NAME="PretendCo"
	readonly DISPLAY_ORGANIZATION_NAME
	
	# The default screen position for dialogs.
	# Available positions are defined by swiftDialog options: topleft, left, bottomleft, top, center (or centre), bottom, topright, right, or bottomright
	DISPLAY_DIALOG_POSITION="topright"
	readonly DISPLAY_DIALOG_POSITION
	
	# Path to the log for the main pseudo workflow:
	PSEUDO_LOG="/var/log/pseudo.log"
	readonly PSEUDO_LOG
	
	# The number of seconds to timeout workflow processes if no progress is reported.
	TIMEOUT_WORKFLOW_SECONDS=300
	readonly TIMEOUT_WORKFLOW_SECONDS
	
	# The number of seconds to timeout while waiting for the user to make a selection in swiftDialog.
	TIMEOUT_DIALOG_SECONDS=60
	readonly TIMEOUT_DIALOG_SECONDS
	
	# The number of seconds to timeout while waiting for a system dialog to open.
	TIMEOUT_OPEN_SECONDS=10
	readonly TIMEOUT_OPEN_SECONDS
	
	# Path to the local application restrictions managed PLIST.
	APP_MANAGED_PLIST="/Library/Managed Preferences/com.apple.applicationaccess.plist"
	readonly APP_MANAGED_PLIST
	
	# Path to the local Extensible SSO managed PLIST.
	SSO_MANAGED_PLIST="/Library/Managed Preferences/com.apple.extensiblesso.plist"
	readonly SSO_MANAGED_PLIST
	
	# Target version for swiftDialog:
	SWIFT_DIALOG_TARGET_VERSION="3.0.1"
	readonly SWIFT_DIALOG_TARGET_VERSION
	
	# URL to the swiftDialog package installer download:
	SWIFT_DIALOG_DOWNLOAD_URL="https://github.com/swiftDialog/swiftDialog/releases/download/v3.0.1/dialog-3.0.1-4955.pkg"
	readonly SWIFT_DIALOG_DOWNLOAD_URL
	
	# Path to the local swiftDialog binary:
	SWIFT_DIALOG_BINARY="/usr/local/bin/dialog"
	readonly SWIFT_DIALOG_BINARY
	
	# Path to the local swiftDialog command file:
	SWIFT_DIALOG_COMMAND_FILE="/var/tmp/dialog.log"
	readonly SWIFT_DIALOG_COMMAND_FILE
	
	# Path to the Jamf Conditional Access binary:
	JAMF_PRO_AAD_BINARY="/Library/Application Support/JAMF/Jamf.app/Contents/MacOS/Jamf Conditional Access.app/Contents/MacOS/Jamf Conditional Access"
	readonly JAMF_PRO_AAD_BINARY
	
	# Path to the Jamf Pro binary:
	JAMF_PRO_BINARY="/usr/local/bin/jamf"
	readonly JAMF_PRO_BINARY
	
	# Path to the Workspace ONE Intelligent Hub CLI binary:
	WORKSPACE_ONE_BINARY="/usr/local/bin/hubcli"
	readonly WORKSPACE_ONE_BINARY
}

# Append input to the command line and log located at ${PSEUDO_LOG}.
log_pseudo() {
	echo -e "$(date +"%a %b %d %T") $(hostname -s) $(basename "$0")[$$]: $*" | tee -a "${PSEUDO_LOG}"
}

# Send input to the command line only.
log_echo() {
	echo -e "$(date +"%a %b %d %T") $(hostname -s) $(basename "$0")[$$]: Not Logged: $*"
}

# This optional command line debugging function can be inserted anywhere to interrupt the workflow and wait for the shell user to press Enter to continue.
interactive_interrupt() {
	log_pseudo "**** P.S.E.U.D.O. ${PSEUDO_VERSION} - ${PSEUDO_DATE} - INTERACTIVE INTERRUPT - PRESS ENTER TO CONTINUE OR CTRL-C TO EXIT ****"
	read -n 1 -p -r > /dev/null 2>&1
}

# Exit the script with no errors.
exit_success() {
	log_pseudo "**** P.S.E.U.D.O. ${PSEUDO_VERSION} - ${PSEUDO_DATE} - EXIT SUCCESS ****"
	exit 0
}

# Exit the script due to an unrecoverable error.
exit_error() {
	log_pseudo "**** P.S.E.U.D.O. ${PSEUDO_VERSION} - ${PSEUDO_DATE} - EXIT ERROR ****"
	exit 1
}

# Used prior to another command or function that should be run as the user.
run_as_user() {
	launchctl asuser "${current_user_id}" sudo -u "${current_user_account_name}" "$@"
}

# Collect parameters for detailed system information and set a variety of parameters.
check_system() {
	macos_version_major=$(sw_vers -productVersion | cut -d'.' -f1) # Expected output: 10, 11, 12
	macos_version_minor=$(sw_vers -productVersion | cut -d'.' -f2) # Expected output: 6, 1
	macos_version_patch=$(sw_vers -productVersion | cut -d'.' -f3) # Expected output: 6, 1
	[[ $macos_version_major -ge 13 ]] && macos_version_extra=$(sw_vers -productVersionExtra | cut -d'.' -f2) # Expected output: (a), (b), (c)
	macos_build=$(sw_vers -buildVersion) # Expected output: 22D68
	macos_title="macOS $(awk '/SOFTWARE LICENSE AGREEMENT FOR/' '/System/Library/CoreServices/Setup Assistant.app/Contents/Resources/en.lproj/OSXSoftwareLicense.rtf' | awk -F 'macOS ' '{print $NF}' | awk '{print substr($0, 0, length($0)-1)}' | sed -e 's/[0-9]//g' | xargs)" # Expected output: macOS Ventura or "*PRE-RELEASE*"
	[[ $(echo "${macos_title}" | grep -c 'PRE-RELEASE') -gt 0 ]] && macos_title="macOS Beta"
	mac_cpu_architecture=$(arch) # Expected output: i386, arm64
	if [[ -n $macos_version_patch ]]; then # macOS version has a patch number.
		[[ -n "${macos_version_extra}" ]] && macos_version_full="${macos_title} ${macos_version_major}.${macos_version_minor}.${macos_version_patch}${macos_version_extra}-${macos_build}"
		[[ -z "${macos_version_extra}" ]] && macos_version_full="${macos_title} ${macos_version_major}.${macos_version_minor}.${macos_version_patch}-${macos_build}"
	else # macOS version does not have a patch number.
		[[ -n "${macos_version_extra}" ]] && macos_version_full="${macos_title} ${macos_version_major}.${macos_version_minor}${macos_version_extra}-${macos_build}"
		[[ -z "${macos_version_extra}" ]] && macos_version_full="${macos_title} ${macos_version_major}.${macos_version_minor}-${macos_build}"
	fi
	[[ "${mac_cpu_architecture}" == "arm64" ]] && log_pseudo "Status: Mac computer with Apple silicon running ${macos_version_full}."
	[[ "${mac_cpu_architecture}" == "i386" ]] && log_pseudo "Status: Mac computer with Intel running ${macos_version_full}."
}

# Set ${current_user_account_name} to the currently logged in GUI user or "FALSE" if there is none or a system account.
check_current_user() {
	current_user_account_name="FALSE"
	local current_user_account_name_response
	current_user_account_name_response=$(scutil <<<"show State:/Users/ConsoleUser" | awk '/Name :/ {$1=$2="";print $0;}' | xargs)
	
	# Make sure we have a "normal" logged in user.
	if [[ -z "${current_user_account_name_response}" ]] || [[ "${current_user_account_name_response}" == "root" ]] || [[ "${current_user_account_name_response}" == "_mbsetupuser" ]] || [[ "${current_user_account_name_response}" == "loginwindow" ]]; then
		return 0
	else # Collect user details.
		current_user_account_name="${current_user_account_name_response}"
		current_user_id=$(id -u "${current_user_account_name}" 2> /dev/null)
		current_user_guid=$(dscl . read "/Users/${current_user_account_name}" GeneratedUID 2> /dev/null | awk '{print $2;}')
		current_user_real_name=$(dscl . read "/Users/${current_user_account_name}" RealName 2> /dev/null | tail -1 | sed -e 's/^RealName: //g' -e 's/^ //g')
		current_user_home_folder=$(dscl . read "/Users/${current_user_account_name}" NFSHomeDirectory 2> /dev/null | awk '{print $2;}')
		# The three following parameters aren't currently used by the pseudo workflow but you never know when they might come in handy in the future.
		current_user_is_admin="FALSE"
		current_user_has_secure_token="FALSE"
		current_user_is_volume_owner="FALSE"
		if [[ -n "${current_user_id}" ]] && [[ -n "${current_user_guid}" ]] && [[ -n "${current_user_real_name}" ]]; then
			[[ $(groups "${current_user_account_name}" 2> /dev/null | grep -c 'admin') -gt 0 ]] && current_user_is_admin="TRUE"
			[[ $(dscl . read "/Users/${current_user_account_name}" AuthenticationAuthority 2> /dev/null | grep -c 'SecureToken') -gt 0 ]] && current_user_has_secure_token="TRUE"
			[[ $(diskutil apfs listcryptousers / 2> /dev/null | grep -c "${current_user_guid}") -gt 0 ]] && current_user_is_volume_owner="TRUE"
		else
			log_pseudo "Error: Unable to determine account details for local user ${current_user_account_name} (${current_user_id})" && workflow_startup_error="TRUE"
		fi
	fi
}

# Evaluate if a process has told the display to not sleep or the user has enabled Focus.
check_current_user_focus() {
	local plutil_response
	plutil_response=$(plutil -extract data.0.storeAssertionRecords.0.assertionDetails.assertionDetailsModeIdentifier raw -o - "${current_user_home_folder}/Library/DoNotDisturb/DB/Assertions.json" 2>&1)
	if [[ $(echo "${plutil_response}" | grep -c 'permission') -gt 0 ]]; then
		log_pseudo "Warning: Unable to determine user Focus mode becaucse the process that started pseudo doesn't have Full Disk Access permissions. If the current user has a Focus mode active then the workflow may fail."
	elif [[ $(echo "${plutil_response}" | grep -c 'com.apple.') -gt 0 ]]; then
		log_pseudo "Warning: The current user has a Focus mode enabled. This may cause the workflow to fail."
	fi
}

# Get the user's default browser and set ${current_user_default_browser}.
check_current_user_default_browser() {
	local plutil_response
	plutil_response=$(/usr/libexec/PlistBuddy -c "Print :LSHandlers" "${current_user_home_folder}/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist" 2>&1)
	if [[ $(echo "${plutil_response}" | grep -c 'Does Not Exist') -gt 0 ]]; then
		log_pseudo "Error: Unable to determine user's default browser becaucse the process that started pseudo doesn't have Full Disk Access permissions."
	else
		current_user_default_browser=$(echo "${plutil_response}" | grep -B1 'https' | head -1 | awk '{print $3}')
		log_pseudo "Status: The default browser for user ${current_user_account_name} is Bundle ID ${current_user_default_browser}."
	fi
	if [[ -z "${current_user_default_browser}" ]]; then
		log_pseudo "Warning: No default browser set for user ${current_user_account_name} so assuming the default of Safari."
		current_user_default_browser="com.apple.safari"
	fi
}

# Validate installed configuration profiles based on "${CHECK_REQUIRED_CONFIG_PROFILES}" option.
check_config_profiles() {
	local check_config_profiles_error
	check_config_profiles_error="FALSE"
	local profiles_result
	profiles_result=$(profiles list -output stdout-xml)
	local previous_ifs
	previous_ifs="${IFS}"
	IFS=','
	local required_config_profiles_array
	read -r -a required_config_profiles_array <<<"${CHECK_REQUIRED_CONFIG_PROFILES}"
	for required_config_profile in "${required_config_profiles_array[@]}"; do
		[[ $(echo "${profiles_result}" | grep -c "${required_config_profile}") -eq 0 ]] && log_pseudo "Error: No installed confiugration profile matches the following required identifier: ${required_config_profile}" && check_config_profiles_error="TRUE"
	done
	IFS="${previous_ifs}"
	[[ "${check_config_profiles_error}" == TRUE ]] && log_pseudo "Error: A required configuration profile is not currently installed." && workflow_startup_error="TRUE"
}

# Prepare pseudo by checking for system, Platform SSO config, and user statuses. This function will exit if any prerequisite isn't succesful.
workflow_startup() {
	local workflow_startup_error
	workflow_startup_error="FALSE"
	# Make sure pseudo is running as root first, otherwise start logging.
	set_defaults
	[[ $(id -u) -ne 0 ]] && log_echo "Exit: pseudo must run with root privileges." && exit 1
	log_pseudo "**** P.S.E.U.D.O. ${PSEUDO_VERSION} - ${PSEUDO_DATE} - STARTUP ****"
	
	# Initial system checks.
	check_system
	[[ $macos_version_major -lt 15 ]] && log_pseudo "Exit: This computer is running macOS ${macos_version_major} and pseudo requires macOS 15 Sequoia or newer." && exit_error
	
	# Validate swiftDialog, if missing or invalid then install and check again.
	killall "dialog" > /dev/null 2>&1
	killall "Dialog" > /dev/null 2>&1
	swift_dialog_app=$(readlink "${SWIFT_DIALOG_BINARY}" 2> /dev/null | sed -e 's/\/Contents.*//')
	if [[ ! -e "${swift_dialog_app}" ]] || [[ ! -e "${SWIFT_DIALOG_BINARY}" ]]; then
		get_swift_dialog
		{ [[ -e "${swift_dialog_app}" ]] && [[ -e "${SWIFT_DIALOG_BINARY}" ]]; } && check_swift_dialog
		[[ "${swift_dialog_valid}" == "FALSE" ]] && log_pseudo "Error: Unable to validate swiftDialog after installation."
	else # swiftDialog is already installed.
		check_swift_dialog
		if [[ "${swift_dialog_valid}" == "FALSE" ]]; then
			get_swift_dialog
			{ [[ -e "${swift_dialog_app}" ]] && [[ -e "${SWIFT_DIALOG_BINARY}" ]]; } && check_swift_dialog
		fi
		[[ "${swift_dialog_valid}" == "FALSE" ]] && log_pseudo "Error: Unable to validate swiftDialog after re-installation."
	fi
	[[ "${swift_dialog_valid}" == "FALSE" ]] && workflow_startup_error="TRUE"
	
	# Make sure that we have an active local user account.
	check_current_user
	if [[ "${workflow_startup_error}" == "FALSE" ]] && [[ "${current_user_account_name}" == "FALSE" ]]; then
		log_pseudo "Status: Waiting for an active user with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
		local wait_for_gui_user_start_epoch
		wait_for_gui_user_start_epoch=$(date +%s)
		while [[ "${current_user_account_name}" == "FALSE" ]]; do
			if [[ $(( wait_for_gui_user_start_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
				log_pseudo "Error: Waiting for an active user timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_startup_error="TRUE"
				break
			fi
			sleep 1
			check_current_user
		done
		[[ "${current_user_account_name}" != "FALSE" ]] && log_pseudo "Status: Waiting for an active user took $(( $(date +%s) - wait_for_gui_user_start_epoch )) seconds to complete."
	fi
	
	# Wait for Dock and Finder to open, this is a good indication the user is fully logged in.
	if [[ "${workflow_startup_error}" == "FALSE" ]] && [[ ! $(pgrep -x "Dock" 2> /dev/null) ]] && [[ ! $(pgrep -x "Finder" 2> /dev/null) ]]; then
		log_pseudo "Status: Waiting for the Dock and Finder to open with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
		local wait_for_gui_apps_start_epoch
		wait_for_gui_apps_start_epoch=$(date +%s)
		while [[ ! $(pgrep -x "Dock" 2> /dev/null) ]] && [[ ! $(pgrep -x "Finder" 2> /dev/null) ]]; do
			if [[ $(( wait_for_gui_apps_start_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
				log_pseudo "Error: Waiting for the Dock and Finder to open timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_startup_error="TRUE"
				break
			fi
			sleep 1
		done
		[[ $(pgrep -x "Dock" 2> /dev/null) ]] && [[ $(pgrep -x "Finder" 2> /dev/null) ]] && log_pseudo "Status: Waiting for the Dock and Finder to open took $(( $(date +%s) - wait_for_gui_user_start_epoch )) seconds to complete."
	fi
	if [[ "${current_user_account_name}" != "FALSE" ]]; then
		log_pseudo "Status: Current active local user is ${current_user_account_name} (${current_user_id})."
		check_current_user_focus
	fi
	
	# Final startup workflow tests.
	[[ -n "${CHECK_REQUIRED_CONFIG_PROFILES}" ]] && check_config_profiles
	[[ "${REPAIR_MODE}" == "TRUE" ]] && log_pseudo "Warning: Repair mode is enabled. The Platform SSO registration workflow will run even if the account was previously registered."
	[[ "${workflow_startup_error}" == "TRUE" ]] && log_pseudo "Exit: Startup workflow failed due to errors." && exit_error
}

# MARK: *** swiftDialog Integration ***
################################################################################

# Check swiftDialog application for validity and version number.
check_swift_dialog() {
	swift_dialog_valid="FALSE"
	local codesign_response
	codesign_response=$(codesign --verify --verbose "${swift_dialog_app}" 2>&1)
	if [[ $(echo "${codesign_response}" | grep -c 'valid on disk') -gt 0 ]]; then
		local version_response
		version_response=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "${swift_dialog_app}/Contents/Info.plist" 2> /dev/null)
		if [[ "${SWIFT_DIALOG_TARGET_VERSION}" == "${version_response}" ]]; then
			swift_dialog_valid="TRUE"
		else
			log_pseudo "Warning: swiftDialog at path is currently version ${version_response}, this does not match target version ${SWIFT_DIALOG_TARGET_VERSION}."
		fi
	else
		log_pseudo "Warning: unable validate signature for swiftDialog:\n${codesign_response}."
	fi
}

# Download and install swiftDialog.
get_swift_dialog() {
	log_pseudo "Status: Attempting to download swiftDialog..."
	local previous_umask
	previous_umask=$(umask)
	umask 077
	local temp_dialog_pkg
	temp_dialog_pkg="$(mktemp).pkg"
	local download_response
	download_response=$(curl --user-agent "${PSEUDO_USER_AGENT}" --connect-timeout "${TIMEOUT_WORKFLOW_SECONDS}" --max-time "${TIMEOUT_WORKFLOW_SECONDS}" --write-out "Total Time: %{time_total}" --location "${SWIFT_DIALOG_DOWNLOAD_URL}" --output "${temp_dialog_pkg}" 2>&1)
	if [[ -f "${temp_dialog_pkg}" ]]; then
		log_pseudo "Status: Successfully downloaded swiftDialog.pkg:\n${download_response}."
		log_pseudo "Status: Attempting to install swiftDialog..."
		local install_response
		install_response=$(installer -verboseR -pkg "${temp_dialog_pkg}" -target / 2>&1)
		if ! { [[ $(echo "${install_response}" | grep -c 'The software was successfully installed.') -gt 0 ]] || [[ $(echo "${install_response}" | grep -c 'The install was successful.') -gt 0 ]]; }; then
			log_pseudo "Error: Unable to install swiftDialog.pkg:\n${install_response}"
		else
			log_pseudo "Status: Successfully installed swiftDialog.pkg:\n${install_response}."
		fi
	else
		log_pseudo "Error: Unable to download swiftDialog.pkg:\n${download_response}."
	fi
	rm -Rf "${temp_dialog_pkg}" > /dev/null 2>&1
	umask "${previous_umask}"
}

# Hide all other visible applications so only swiftDialog is visible.
focus_dialog() {
	osascript > /dev/null 2>&1 <<EOAS
tell application "Finder"
	if (count of windows) is not 0 then
		tell application "Finder" to close every window
		delay 0.1
	end if
end tell
tell application "System Events"
	set visibleApps to every process whose visible is true and name is not "Dialog" and name is not "Finder" and bundle identifier is not "${do_not_hide_bundle_id}"
	repeat with anApp in visibleApps
		tell anApp to set visible to false
		delay 0.1
	end repeat
end tell
if application "Dialog" is running then
	tell application "System Events"
		tell application process "Dialog" to set frontmost to true
	end tell
end if
EOAS
}

# Hide all visible applications except for swiftDialog looping every second. This function should be backgrounded and killed when complete.
focus_dialog_loop() {
	while true; do
		focus_dialog
		sleep 1
	done
}

# MARK: *** Jamf Pro Integration ***
################################################################################

# Check to see if the Jamf Pro device compliance registration window is open and return its status as "TRUE" or "FALSE".
check_jamfaad_interface_status() {
	local psso_jamfaad_active_result
	psso_jamfaad_active_result=$(osascript 2> /dev/null <<EOAS
tell application "System Events"
	if exists process "Jamf Conditional Access" then
		if exists window 1 of application process "Jamf Conditional Access" then
			return "TRUE"
		else
			return "FALSE"
		end if
	else
		return "FALSE"
	end if
end tell
EOAS
	)
	echo "${psso_jamfaad_active_result}"
}

# Hide all other visible applications so only Jamf Pro device compliance registration is visible.
focus_jamfaad_registration() {
	osascript > /dev/null 2>&1 <<EOAS
tell application "Finder"
	if (count of windows) is not 0 then
		tell application "Finder" to close every window
		delay 0.1
	end if
end tell
tell application "System Events"
	set visibleApps to every process whose visible is true and name is not "Jamf Conditional Access" and name is not "Dialog" and name is not "Finder" and bundle identifier is not "${do_not_hide_bundle_id}"
	repeat with anApp in visibleApps
		tell anApp to set visible to false
		delay 0.1
	end repeat
	if exists window 1 of application process "Jamf Conditional Access" then
		tell process "Jamf Conditional Access" to set frontmost to true
	end if
end tell
EOAS
}

# Open a swiftDialog to inform the user that they need to complete the Jamf Pro device compliance registration.
open_dialog_jamfaad_active() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: jamfAAD Active"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration" \
	--message "**Please select your account credentials to complete the Jamf Conditional Access registration.**" \
	--icon "${psso_dialog_icon}" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Update Jamf Pro device compliance and inventory if workflow was successful.
jamf_pro_update_inventory() {
	update_inventory_error="FALSE"
	if [[ -e "${JAMF_PRO_AAD_BINARY}" ]]; then
		log_pseudo "Status: Updating Jamf Pro device compliance..."
		local psso_jamfaad_end_epoch
		local temp_jamfaad_response
		temp_jamfaad_response="$(mktemp).log"
		run_as_user "${JAMF_PRO_AAD_BINARY}" gatherAADInfo > "${temp_jamfaad_response}" 2>&1 &
		sleep 1
		if [[ "$(check_jamfaad_interface_status)" == "TRUE" ]]; then
			log_pseudo "Status: Waiting for user interactive Jamf Pro device compliance registration with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
			open_dialog_jamfaad_active
			psso_jamfaad_end_epoch=$(date +%s)
			while [[ "$(check_jamfaad_interface_status)" == "TRUE" ]]; do
				if [[ $(( psso_jamfaad_end_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
					log_pseudo "Error: User interactive Jamf Pro device compliance registration timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && update_inventory_error="TRUE"
					break
				fi
				focus_jamfaad_registration
				sleep 1
			done
			if [[ "${update_inventory_error}" == "FALSE" ]]; then
				log_pseudo "Status: User interactive Jamf Pro device compliance registration took $(( $(date +%s) - psso_jamfaad_end_epoch )) seconds to complete."
			else
				killall "Jamf Conditional Access" > /dev/null 2>&1
			fi
		fi
		if [[ "$(check_jamfaad_interface_status)" == "FALSE" ]] && [[ "${update_inventory_error}" == "FALSE" ]]; then
			if [[ $(cat "${temp_jamfaad_response}" | grep -c 'AAD ID acquired') -gt 0 ]] && [[ $(cat "${temp_jamfaad_response}" | grep -c "${current_user_account_name}") -gt 0 ]]; then
				log_pseudo "Status: Jamf Pro device compliance appears to be registered for user ${current_user_account_name}."
			else
				log_pseudo "Error: Unexpected Jamf Pro device compliance verification result:\n$(cat "${temp_jamfaad_response}")" && update_inventory_error="TRUE"
			fi
		else
			log_pseudo "Error: Could not validate Jamf Pro device compliance registration." && update_inventory_error="TRUE"
		fi
		rm -Rf "${temp_jamfaad_response}" > /dev/null 2>&1
	else
		log_pseudo "Warning: Could not locate Jamf Conditional Access binary in the expected location."
	fi
	[[ "${psso_workflow_main_active}" == "TRUE" ]] && open_dialog_psso_success & disown
	if [[ -e "${JAMF_PRO_BINARY}" ]]; then
		log_pseudo "Status: Updating Jamf Pro inventory..."
		local jamf_recon_response
		jamf_recon_response=$("${JAMF_PRO_BINARY}" recon -verbose 2>&1)
		if [[ $(echo "${jamf_recon_response}" | grep -c 'Submitting data') -gt 0 ]]; then
			log_pseudo "Status: Jamf Pro inventory successfully updated."
		else
			log_pseudo "Error: Could not update Jamf Pro inventory:\n${jamf_recon_response}" && update_inventory_error="TRUE"
		fi
	else
		log_pseudo "Error: Could not locate the Jamf Pro binary in the expected location." && update_inventory_error="TRUE"
	fi
}

# MARK: *** Workspace ONE Integration ***
################################################################################

# Open a dialog to inform the user about Workspace ONE registration.
open_dialog_workspace_one_sync() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	"${SWIFT_DIALOG_BINARY}" \
	--title "Device Registration" \
	--message "A Workspace ONE Intelligent Hub window will now appear.  \n  \nPlease select your account from the list and click \"Continue\"." \
	--icon "${psso_dialog_icon}" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text "OK" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop
}

# Update Workspace ONE sensors after Platform SSO enrollment.
workspace_one_update_sensors() {
	log_pseudo "Status: Updating Workspace ONE sensors..."
	
	# Convert comma-separated string to array
	local previous_ifs
	previous_ifs="${IFS}"
	IFS=','
	local sensor_array
	read -r -a sensor_array <<< "${UPDATE_WORKSPACE_ONE_SENSORS}"
	
	for sensor_name in "${sensor_array[@]}"; do
		[[ -z "${sensor_name}" ]] && continue  # Skip empty entries
		
		log_pseudo "Status: Triggering Workspace ONE sensor: ${sensor_name}"
		local sensor_response
		local sensor_success="FALSE"
		
		# Trigger the sensor
		sensor_response=$("${WORKSPACE_ONE_BINARY}" sensors --trigger "${sensor_name}" 2>&1)
		
		# Check for success message
		if [[ $(echo "${sensor_response}" | grep -c 'Successfully executed the Sensor and reported the result to UEM.') -gt 0 ]]; then
			sensor_success="TRUE"
			log_pseudo "Status: Successfully updated Workspace ONE sensor: ${sensor_name}"
		fi
		
		if [[ "${sensor_success}" == "FALSE" ]]; then
			log_pseudo "Error: Workspace ONE sensor update timed out or failed for: ${sensor_name}\n${sensor_response}" && update_inventory_error="TRUE"
		fi
	done
	log_pseudo "Status: Workspace ONE sensor updates completed."
	IFS="${previous_ifs}"
}

# Update Workspace ONE Intelligent Hub inventory if workflow was successful.
workspace_one_update_inventory() {
	update_inventory_error="FALSE"
	[[ ! -e "${WORKSPACE_ONE_BINARY}" ]] && log_pseudo "Error: Could not locate the Workspace ONE binary in the expected location: ${WORKSPACE_ONE_BINARY}" && update_inventory_error="TRUE"
	log_pseudo "Status: Syncing device inventory with Workspace ONE Intelligent Hub..."
	open_dialog_workspace_one_sync
	local hubcli_response
	hubcli_response=$("${WORKSPACE_ONE_BINARY}" sync 2>&1)
	if [[ $(echo "${hubcli_response}" | grep -c 'Sync started.') -gt 0 ]]; then
		log_pseudo "Status: Workspace ONE inventory sync successfully started."
	else
		log_pseudo "Error: Could not start Workspace ONE inventory sync:\n${hubcli_response}" && update_inventory_error="TRUE"
	fi
	
	# Update sensors if enabled
	[[ -n "${UPDATE_WORKSPACE_ONE_SENSORS}" ]] && workspace_one_update_sensors
}

# MARK: *** Touch ID Workflow ***
################################################################################

# Check to see if the current user has Touch ID enabled and return its status as "TRUE" or "FALSE".
check_touch_id_user_status() {
	local bioutil_user_ids
	bioutil_user_ids=($(bioutil -c -s | awk '/User/ {print $2 $3}'))
	if [[ $(echo "${bioutil_user_ids[*]}" | grep -c "${current_user_id}") -gt 0 ]]; then
		echo "TRUE"
	else
		echo "FALSE"
	fi
}

# Open the Touch ID System Settings window and return status as "TRUE" or "FALSE".
open_touch_id_system_settings() {
	killall "System Settings" > /dev/null 2>&1
	run_as_user open "x-apple.systempreferences:com.apple.Touch-ID-Settings.extension"
	local open_touch_id_system_settings_result
	open_touch_id_system_settings_result=$(osascript 2> /dev/null <<EOAS
set openTimeout to (current date) + ${TIMEOUT_OPEN_SECONDS}
tell application "System Events"
	repeat while not (exists window 1 of application process "System Settings")
		delay 0.1
		if (current date) > openTimeout then return "FALSE"
	end repeat
	return "TRUE"
end tell
EOAS
	)
	echo "${open_touch_id_system_settings_result}"
}

# Check the status of the Touch ID System Settings window and return its status as "OPEN", "ACTIVE", or "FALSE".
check_touch_id_settings_status() {
	local touch_id_settings_status_result
	touch_id_settings_status_result=$(osascript 2> /dev/null <<EOAS
if application "System Settings" is running then
	tell application "System Events"
		if title of window 1 of process "System Settings" contains "Touch ID" then
			if exists sheet 1 of window 1 of process "System Settings" then
				return "ACTIVE"
			else
				return "OPEN"
			end if
		else
			return "FALSE"
		end if
	end tell
else
	return "FALSE"
end if
EOAS
	)
	echo "${touch_id_settings_status_result}"
}

# Hide all other visible applications so only the Touch ID System Settings is visible.
focus_touch_id_settings() {
	osascript > /dev/null 2>&1 <<EOAS
tell application "Finder"
	if (count of windows) is not 0 then
		tell application "Finder" to close every window
		delay 0.1
	end if
end tell
tell application "System Events"
	set visibleApps to every process whose visible is true and name is not "System Settings" and name is not "Dialog" and name is not "Finder" and bundle identifier is not "${do_not_hide_bundle_id}"
	repeat with anApp in visibleApps
		tell anApp to set visible to false
		delay 0.1
	end repeat
	tell process "System Settings" to set frontmost to true
end tell
EOAS
}

# Open an interactive swiftDialog informing the user that they are required to enable Touch ID and set ${dialog_touch_id_result}.
open_dialog_touch_id_required() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	focus_dialog_loop &
	local focus_dialog_loop_pid
	focus_dialog_loop_pid=$!
	disown $focus_dialog_loop_pid
	log_pseudo "Dialog Open: Touch ID Setup Required"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Touch ID Setup Required" \
	--message "**Touch ID is required for all Mac computers at ${DISPLAY_ORGANIZATION_NAME}.**<br><br>Touch ID provides enhanced security and convenience by allowing you to authenticate using the Mac computer's fingerprint sensor." \
	--icon "SF=touchid,palette=primary,accent,none" \
	--small \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--timer "${TIMEOUT_DIALOG_SECONDS}" \
	--hidetimerbar \
	--button1text "Enable Touch ID" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop
	dialog_touch_id_result=$?
	log_pseudo "Dialog Closed: Touch ID Setup Required"
	kill -9 "${focus_dialog_loop_pid}" > /dev/null 2>&1
}

# Open an interactive swiftDialog asking the user if they want to enable Touch ID and set ${dialog_touch_id_result}.
open_dialog_touch_id_optional() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	focus_dialog_loop &
	local focus_dialog_loop_pid
	focus_dialog_loop_pid=$!
	disown $focus_dialog_loop_pid
	log_pseudo "Dialog Open: Touch ID Setup Optional"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Touch ID Setup" \
	--message "**Please take a few moments to enable Touch ID.**<br><br>Touch ID provides enhanced security and convenience by allowing you to authenticate using the Mac computer's fingerprint sensor." \
	--icon "SF=touchid,palette=primary,accent,none" \
	--small \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--timer "${TIMEOUT_DIALOG_SECONDS}" \
	--hidetimerbar \
	--button1text "Enable Touch ID" \
	--button2text "Skip" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop
	dialog_touch_id_result=$?
	log_pseudo "Dialog Closed: Touch ID Setup Optional"
	kill -9 "${focus_dialog_loop_pid}" > /dev/null 2>&1
}

# Open a swiftDialog to assist while the user enables Touch ID.
open_dialog_touch_id_start() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Touch ID Start"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Touch ID Setup" \
	--message "**Enable Touch ID by adding at least one fingerprint in the Touch ID settings.**" \
	--icon "SF=touchid,palette=primary,accent,none" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--timer "${TIMEOUT_DIALOG_SECONDS}" \
	--hidetimerbar \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Open a swiftDialog to inform the user that Touch ID is enabled.
open_dialog_touch_id_success() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Touch ID Success"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Touch ID Enabled" \
	--message "**Thank you for enabling Touch ID!**<br><br>You can now authenticate on this Mac using your fingerprint. You can register additional fingerprints or click \"OK\" to close the Touch ID settings." \
	--icon "SF=touchid,palette=primary,accent,none" \
	--small \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--timer "${TIMEOUT_DIALOG_SECONDS}" \
	--hidetimerbar \
	--button1text "OK" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop
	return $?
}

# Open an interactive swiftDialog informing the user that the Touch ID workflow has failed.
open_dialog_touch_id_failed() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	focus_dialog
	log_pseudo "Dialog Open: Touch ID Failed"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Touch ID Setup Failed" \
	--message "**Touch ID setup has failed.**<br><br>Please contact your administrator if this issue persists." \
	--icon caution \
	--overlayicon "SF=touchid,palette=primary,accent,none" \
	--small \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text "OK" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# The full workflow to check Touch ID status and if required open interfaces and dialogs to enable Touch ID.
workflow_touch_id() {
	local workflow_touch_id_error
	workflow_touch_id_error="FALSE"
	touch_id_workflow_active="FALSE"
	
	# Initial Touch ID system configuration checks. This sets ${touch_id_hardware_status}
	local ioreg_result
	ioreg_result=$(ioreg -l 2> /dev/null)
	if [[ $(echo "${ioreg_result}" | grep -c -e '\"AppleBiometricSensor\"=[1-9]') -gt 0 ]]; then
		touch_id_hardware_status="INTERNAL"
	elif [[ $(echo "${ioreg_result}" | grep -c -e 'with Touch ID') -gt 0 ]]; then
		touch_id_hardware_status="EXTERNAL"
	else
		touch_id_hardware_status="FALSE"
	fi
	if [[ "${touch_id_hardware_status}" != "FALSE" ]]; then
		[[ $(/usr/libexec/PlistBuddy -c "Print :allowFingerprintForUnlock" "${APP_MANAGED_PLIST}" 2> /dev/null) == "false" ]] && touch_id_hardware_status="DISABLED"
		[[ $(/usr/libexec/PlistBuddy -c "Print :allowFingerprintModification" "${APP_MANAGED_PLIST}" 2> /dev/null) == "false" ]] && touch_id_hardware_status="DISABLED"
	fi
	
	# Check Touch ID user status and if it's already enabled then skip the workflow.
	if [[ "${touch_id_hardware_status}" == "INTERNAL" ]] || [[ "${touch_id_hardware_status}" == "EXTERNAL" ]]; then
		local touch_id_user_status
		touch_id_user_status=$(check_touch_id_user_status)
		[[ "${touch_id_user_status}" == "TRUE" ]] && log_pseudo "Status: Touch ID is already enabled for local user ${current_user_account_name} (${current_user_id})." && return 0
	fi
	
	# Given the ${TOUCH_ID_CONFIG} option, handle the initial Touch ID registration dialog.
	if [[ "${TOUCH_ID_CONFIG}" == "REQUIRED" ]]; then
		[[ "${touch_id_hardware_status}" == "FALSE" ]] && log_pseudo "Warning: Can't enforce Touch ID enablement because this system does not have access to Touch ID hardware." && return 0
		[[ "${touch_id_hardware_status}" == "DISABLED" ]] && log_pseudo "Warning: Can't enforce Touch ID enablement because a restrictions configuration profile is not allowing Touch ID." && return 0
		log_pseudo "Status: Informing user that Touch ID is required and will be configured for local user ${current_user_account_name} (${current_user_id})."
		open_dialog_touch_id_required
	elif [[ "${TOUCH_ID_CONFIG}" == "OPTIONAL" ]]; then
		[[ "${touch_id_hardware_status}" == "FALSE" ]] && log_pseudo "Warning: Can't ask user to enable Touch ID because this system does not have access to Touch ID hardware." && return 0
		[[ "${touch_id_hardware_status}" == "DISABLED" ]] && log_pseudo "Warning: Can't ask user to enable Touch ID because a restrictions configuration profile is not allowing Touch ID." && return 0
		log_pseudo "Status: Asking local user ${current_user_account_name} (${current_user_id}) if they want to enable optional Touch ID."
		open_dialog_touch_id_optional
	else
		log_pseudo "Status: Touch ID workflow is disabled."
		return 0
	fi
	if [[ "${dialog_touch_id_result}" -eq 2 ]]; then
		log_pseudo "Status: The user chose to skip the optional Touch ID enablement." && return 0
	elif [[ "${dialog_touch_id_result}" -eq 4 ]]; then
		log_pseudo "Error: The initial Touch ID dialog timed out after ${TIMEOUT_DIALOG_SECONDS} seconds." && workflow_touch_id_error="TRUE"
	elif [[ "${dialog_touch_id_result}" -gt 0 ]]; then
		log_pseudo "Error: The initial Touch ID dialog returned unexpected result: ${dialog_touch_id_result}" && workflow_touch_id_error="TRUE"
	fi
	
	# At this point it's time to open the Touch ID system settings.
	if [[ "${workflow_touch_id_error}" == "FALSE" ]] && [[ "${touch_id_user_status}" == "FALSE" ]]; then
		log_pseudo "Status: Starting Touch ID workflow with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
		touch_id_workflow_active="TRUE"
		local touch_id_settings_status
		local touch_id_workflow_start_epoch
		touch_id_workflow_start_epoch=$(date +%s)
		log_pseudo "Status: Attempting to open Touch ID System Settings..."
		[[ $(open_touch_id_system_settings) == "FALSE" ]] && log_pseudo "Error: Opening Touch ID System Settings timed out after ${TIMEOUT_OPEN_SECONDS} seconds." && workflow_touch_id_error="TRUE"
		[[ "${workflow_touch_id_error}" == "FALSE" ]] && open_dialog_touch_id_start
		while [[ "${workflow_touch_id_error}" == "FALSE" ]] && { [[ "${touch_id_user_status}" == "FALSE" ]] || { [[ "${touch_id_user_status}" == "TRUE" ]] && [[ "${touch_id_settings_status}" == "ACTIVE" ]]; }; }; do
			if [[ $(( touch_id_workflow_start_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
				log_pseudo "Error: Touch ID workflow timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_touch_id_error="TRUE"
				break
			fi
			focus_touch_id_settings
			touch_id_settings_status=$(check_touch_id_settings_status)
			if [[ "${touch_id_settings_status}" == "FALSE" ]]; then
				log_pseudo "Status: Attempting to re-open Touch ID System Settings (the user likely closed the Touch ID settings)..."
				[[ $(open_touch_id_system_settings) == "FALSE" ]] && log_pseudo "Error: Opening Touch ID System Settings timed out after ${TIMEOUT_OPEN_SECONDS} seconds." && workflow_touch_id_error="TRUE"
			fi
			sleep 1
			touch_id_user_status=$(check_touch_id_user_status)
		done
	fi
	
	# Touch ID has been enabled, ask if the user wants to enable another fingerprint.
	if [[ "${workflow_touch_id_error}" == "FALSE" ]] && [[ "${touch_id_user_status}" == "TRUE" ]]; then
		focus_touch_id_settings
		open_dialog_touch_id_success
		dialog_touch_id_result=$?
		if [[ "${dialog_touch_id_result}" -eq 4 ]]; then
			log_pseudo "Error: The initial Touch ID dialog timed out after ${TIMEOUT_DIALOG_SECONDS} seconds." && workflow_touch_id_error="TRUE"
		elif [[ "${dialog_touch_id_result}" -gt 0 ]]; then
			log_pseudo "Error: The initial Touch ID dialog returned unexpected result: ${dialog_touch_id_result}" && workflow_touch_id_error="TRUE"
		fi
	fi
	
	# If there are any Touch ID workflow errors then present a failure dialog and exit.
	killall "System Settings" > /dev/null 2>&1
	if [[ "${workflow_touch_id_error}" == "FALSE" ]]; then
		log_pseudo "Status: Touch ID is now enabled for local user ${current_user_account_name} (${current_user_id}). The Touch ID workflow took $(( $(date +%s) - touch_id_workflow_start_epoch )) seconds to complete."
	else
		[[ "${touch_id_workflow_active}" == "TRUE" ]] && open_dialog_touch_id_failed & disown
		log_pseudo "Exit: Touch ID workflow failed due to errors." && exit_error
	fi
}

# MARK: *** Platform SSO Workflow ***
################################################################################

# Check to see if the current user is registered for Platform SSO and set ${psso_user_status_dscl}, ${psso_user_status_login_name}, ${psso_user_status_login_type}, "${psso_user_status_state}, and ${psso_user_status_smartcard_token_id} accordingly.
check_psso_user_status() {
	local dscl_result
	dscl_result=$(dscl . read /Users/"${current_user_account_name}" dsAttrTypeStandard:AltSecurityIdentities 2> /dev/null | awk -F'SSO:' '/PlatformSSO/ {print $2}')
	if [[ -n "${dscl_result}" ]]; then
		psso_user_status_dscl="${dscl_result}"
		local app_sso_response
		app_sso_response=$(run_as_user app-sso platform -s | sed -e '1,/User Configuration:/d' | tr -d '\\')
		psso_user_status_login_name=$(echo "${app_sso_response}" | jq -r '.userLoginConfiguration.loginUserName' 2> /dev/null)
		psso_user_status_login_type=$(echo "${app_sso_response}" | jq -r '.loginType' 2> /dev/null)
		psso_user_status_state=$(echo "${app_sso_response}" | jq -r '.state' 2> /dev/null)
		[[ $(echo "${psso_login_type}" | grep -c 'SmartCard') -gt 0 ]] && psso_user_status_smartcard_token_id=$(echo "${app_sso_response}" | jq -r '.smartCardTokenId' 2> /dev/null)
	fi
	[[ -z "${dscl_result}" ]] && psso_user_status_dscl="FALSE"
	[[ -z "${psso_user_status_login_name}" ]] && psso_user_status_login_name="FALSE"
	[[ -z "${psso_user_status_login_type}" ]] && psso_user_status_login_type="FALSE"
	[[ -z "${psso_user_status_state}" ]] && psso_user_status_state="FALSE"
	[[ -z "${psso_user_status_smartcard_token_id}" ]] && psso_user_status_smartcard_token_id="FALSE"
}

# Pre-enable relevant password AutoFill extensions.
enable_psso_autofill_extensions() {
	local previous_ifs
	previous_ifs="${IFS}"
	IFS=$'\n'
	local plugin_kit_response
	[[ "${psso_extension_identifier}" == "com.microsoft.CompanyPortalMac.ssoextension" ]] && plugin_kit_response=($(run_as_user pluginkit -m 2> /dev/null | grep 'com.microsoft.CompanyPortalMac'))
	[[ "${psso_extension_identifier}" == "com.okta.mobile.auth-service-extension" ]] && plugin_kit_response=($(run_as_user pluginkit -m 2> /dev/null | grep 'com.okta.mobile'))
	for plugin_kit_item in "${plugin_kit_response[@]}"; do
		[[ $(echo "${plugin_kit_item}" | grep -c -e '\+    ') -gt 0 ]] && log_pseudo "Status: The AutoFill extension with ID $(echo "${plugin_kit_item}" | awk -F' ' '{print $2}' | sed -e 's/(.*$//') is already enabled."
		if [[ $(echo "${plugin_kit_item}" | grep -c -e '-    ') -gt 0 ]]; then
			log_pseudo "Status: Re-enabling AutoFill extension with ID $(echo "${plugin_kit_item}" | awk -F' ' '{print $2}' | sed -e 's/(.*$//')."
			run_as_user pluginkit -e use -i "$(echo "${plugin_kit_item}" | awk -F' ' '{print $2}' | sed -e 's/(.*$//')" > /dev/null 2>&1
		elif [[ $(echo "${plugin_kit_item}" | grep -c -e '\+    ') -eq 0 ]]; then
			log_pseudo "Status: Enabling AutoFill extension with ID $(echo "${plugin_kit_item}" | awk -F' ' '{print $1}' | sed -e 's/(.*$//')."
			run_as_user pluginkit -e use -i "$(echo "${plugin_kit_item}" | awk -F' ' '{print $1}' | sed -e 's/(.*$//')" > /dev/null 2>&1
		fi
	done
	IFS="${previous_ifs}"
}

# Check the status of Platform SSO registration dialog and return its status as "OPEN", "ACTIVE", "AUTOFILL", "CLOSE", or "FALSE".
check_psso_registration_status() {
	local psso_registration_status_result
	psso_registration_status_result=$(osascript 2> /dev/null <<EOAS
if application "AppSSOAgent" is running then
	tell application "System Events"
		set windowCount to count of every window of application process "AppSSOAgent"
		if windowCount is greater than 1 then
			repeat with i from 1 to windowCount
				set allElements to entire contents of window i of application process "AppSSOAgent"
				repeat with aElement in allElements
					if name of aElement contains "autofill" then
						return "AUTOFILL"
					end if
				end repeat
			end repeat
			return "ACTIVE"
		else if windowCount is equal to 1 then
			if (count of every sheet of window 1 of application process "AppSSOAgent") is greater than 0 then
				return "ACTIVE"
			else -- No open sheets.
				if (count of every button of window 1 of application process "AppSSOAgent") is greater than 1 then
					return "OPEN"
				else -- Only one button.
					return "CLOSE"
				end if
			end if
		else -- No open windows.
			return "FALSE"
		end if
	end tell
else
	return "FALSE"
end if
EOAS
	)
	echo "${psso_registration_status_result}"
}

# Check to see if the SmartCard authentication window is open and return its status as "TRUE" or "FALSE".
check_psso_smartcard_auth_status() {
	local psso_smartcard_auth_active_result
	psso_smartcard_auth_active_result=$(osascript 2> /dev/null <<EOAS
tell application "System Events"
	if exists process "coreautha" then
		if exists window 1 of application process "coreautha" then
			return "TRUE"
		else
			return "FALSE"
		end if
	else
		return "FALSE"
	end if
end tell
EOAS
	)
	echo "${psso_smartcard_auth_active_result}"
}

# Attempt to open Platform SSO registration via System Settings and return status as "TRUE" or "FALSE".
open_psso_registration() {
	killall "AppSSOAgent" > /dev/null 2>&1
	killall "System Settings" > /dev/null 2>&1
	run_as_user open "x-apple.systempreferences:com.apple.Users-Groups-Settings.extension"
	local open_psso_registration_result
	open_psso_registration_result=$(osascript 2> /dev/null <<EOAS
set openTimeout to (current date) + ${TIMEOUT_OPEN_SECONDS}
tell application "System Events"
	repeat while not (exists window 1 of application process "System Settings")
		delay 0.1
		if (current date) > openTimeout then return "FALSE"
	end repeat
	tell application process "System Settings" to set frontmost to true
	repeat while not (exists button 2 of group 2 of scroll area 1 of group 1 of group 3 of splitter group 1 of group 1 of window 1 of application process "System Settings")
		delay 0.1
		if (current date) > openTimeout then return "FALSE"
	end repeat
	tell button 2 of group 2 of scroll area 1 of group 1 of group 3 of splitter group 1 of group 1 of window 1 of application process "System Settings" to perform action "AXPress"
	repeat while not (exists button 1 of group 2 of scroll area 1 of group 1 of sheet 1 of window 1 of application process "System Settings")
		delay 0.1
		if (current date) > openTimeout then return "FALSE"
	end repeat
	tell button 1 of group 2 of scroll area 1 of group 1 of sheet 1 of window 1 of application process "System Settings" to perform action "AXPress"
	repeat while not (exists window 1 of application process "AppSSOAgent")
		delay 0.1
		if (current date) > openTimeout then return "FALSE"
	end repeat
	tell application "System Settings" to quit
	return "TRUE"
end tell
EOAS
	)
	echo "${open_psso_registration_result}"
}

# Hide all other visible applications so only Platform SSO registration is visible.
focus_psso_registration() {
	osascript > /dev/null 2>&1 <<EOAS
tell application "Finder"
	if (count of windows) is not 0 then
		tell application "Finder" to close every window
		delay 0.1
	end if
end tell
tell application "System Events"
	set visibleApps to every process whose visible is true and name is not "AppSSOAgent" and name is not "Single Sign-On" and name is not "coreautha" and name is not "Dialog" and name is not "Finder" and bundle identifier is not "${do_not_hide_bundle_id}"
	repeat with anApp in visibleApps
		tell anApp to set visible to false
		delay 0.1
	end repeat
	if (exists window 1 of application process "coreautha") then
		tell process "coreautha" to set frontmost to true
	else
		tell process "Single Sign-On" to set frontmost to true
	end if
end tell
EOAS
}

# Close the Platform SSO registration AutoFill window.
close_psso_registration_autofill() {
	osascript > /dev/null 2>&1 <<EOAS
if application "AppSSOAgent" is running then
	tell application "System Events"
		set windowCount to count of every window of application process "AppSSOAgent"
		repeat with i from 1 to windowCount
			set allElements to entire contents of window i of application process "AppSSOAgent"
			repeat with aElement in allElements
				if name of aElement contains "autofill" then
					set autoFillWindow to window i of application process "AppSSOAgent"
					exit repeat
				end if
			end repeat
			if autoFillWindow is not missing value then exit repeat
		end repeat
		if autoFillWindow is not missing value then
			set buttonCount to count of every button of autoFillWindow
			repeat with i from 1 to buttonCount
				if (get value of attribute "AXIdentifier" of button i of autoFillWindow) is equal to "action-button-2" then
					tell button i of autoFillWindow to perform action "AXPress"
					exit repeat
				end if
			end repeat
		end if
	end tell
end if
EOAS
}

# Close the Platform SSO registration window.
close_psso_registration() {
	osascript > /dev/null 2>&1 <<EOAS
if application "AppSSOAgent" is running then
	tell application "System Events"
		if (count of every window of application process "AppSSOAgent") is equal to 1 then
			if (get value of attribute "AXIdentifier" of button 1 of window 1 of application process "AppSSOAgent") is equal to "Primary Button" then
				tell button 1 of window 1 of application process "AppSSOAgent" to perform action "AXPress"
			end if
		end if
	end tell
end if
EOAS
}

# Open an interactive swiftDialog informing the user that they are required to enable Platform SSO and set ${dialog_psso_required_result}.
open_dialog_psso_required() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	focus_dialog_loop &
	local focus_dialog_loop_pid
	focus_dialog_loop_pid=$!
	disown $focus_dialog_loop_pid
	log_pseudo "Dialog Open: Platform SSO Registration Required"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration Required" \
	--message "**Platform SSO is required for all Mac computers at ${DISPLAY_ORGANIZATION_NAME}.**<br><br>Platform SSO provides enhanced security and convenience by integrating this Mac with your ${DISPLAY_ORGANIZATION_NAME} ${psso_dialog_idp_string} account." \
	--icon "${psso_dialog_icon}" \
	--small \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--timer "${TIMEOUT_DIALOG_SECONDS}" \
	--hidetimerbar \
	--button1text "Register Platform SSO" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop
	dialog_psso_required_result=$?
	log_pseudo "Dialog Closed: Platform SSO Registration Required"
	kill -9 "${focus_dialog_loop_pid}" > /dev/null 2>&1
}

# Open a swiftDialog to inform the user that they need to attach a SmartCard.
open_dialog_smartcard_required() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Platform SSO SmartCard Required"
	"${SWIFT_DIALOG_BINARY}" \
	--title "SmartCard Required" \
	--message "**Please attach your SmartCard to continue registration for Platform SSO.**" \
	--icon "SF=key.card,palette=accent,primary,none" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Open a swiftDialog to inform the user that they need to register with Platform SSO.
open_dialog_psso_start() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Platform SSO Start"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration Required" \
	--message "**Please click the \"Continue\" button to sign in and register with Platform SSO.**" \
	--icon "${psso_dialog_icon}" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Open a swiftDialog to acknowledge that the user is actively registering with Platform SSO.
open_dialog_psso_active() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Platform SSO Active"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration" \
	--message "**Please provide your account credentials to proceed with the Platform SSO registration.**" \
	--icon "${psso_dialog_icon}" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Open a swiftDialog to inform the user that they are almost done with the Password authentication workflow.
open_dialog_password_sync() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Platform SSO Password Sync"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration" \
	--message "**Please enter your ${psso_display_name} password one more time to enable it for macOS account login.**" \
	--icon "SF=person.badge.key,palette=primary,accent,none" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Open a swiftDialog to inform the user that they are almost done with the SmartCard authentication workflow.
open_dialog_smartcard_pairing() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	log_pseudo "Dialog Open: Platform SSO SmartCard Pairing"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration" \
	--message "**Please enter your SmartCard PIN one more time to enable it for macOS account login.**" \
	--icon "SF=key.card,palette=accent,primary,none" \
	--mini \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text none \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# Open a swiftDialog to inform the user that Platform SSO registration was successful.
open_dialog_psso_success() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	if [[ $(echo "${psso_login_type}" | grep -c 'Password') -gt 0 ]]; then
		log_pseudo "Dialog Open: Platform SSO Password Success"
		"${SWIFT_DIALOG_BINARY}" \
		--title "Platform SSO Enabled" \
		--message "**Thank you for enabling Platform SSO!**<br><br>You can now log in to this Mac using your ${psso_display_name} password. Also, applications and services that use your ${psso_display_name} account should now sign in automatically." \
		--icon "${psso_dialog_icon}" \
		--small \
		--position "${DISPLAY_DIALOG_POSITION}" \
		--button1text "OK" \
		--quitkey p \
		--hidedefaultkeyboardaction \
		--ontop &
	elif [[ $(echo "${psso_login_type}" | grep -c 'SmartCard') -gt 0 ]]; then
		log_pseudo "Dialog Open: Platform SSO SmartCard Success"
		"${SWIFT_DIALOG_BINARY}" \
		--title "Platform SSO Enabled" \
		--message "**Thank you for enabling Platform SSO!**<br><br>You can now log in to this Mac using your SmartCard and PIN. Also, applications and services that use your ${psso_display_name} account should now sign in automatically." \
		--icon "${psso_dialog_icon}" \
		--small \
		--position "${DISPLAY_DIALOG_POSITION}" \
		--button1text "OK" \
		--quitkey p \
		--hidedefaultkeyboardaction \
		--ontop &
	else
		log_pseudo "Dialog Open: Platform SSO Secure Enclave Success"
		"${SWIFT_DIALOG_BINARY}" \
		--title "Platform SSO Enabled" \
		--message "**Thank you for enabling Platform SSO!**<br><br>Applications and services that use your ${psso_display_name} account should now sign in automatically." \
		--icon "${psso_dialog_icon}" \
		--small \
		--position "${DISPLAY_DIALOG_POSITION}" \
		--button1text "OK" \
		--quitkey p \
		--hidedefaultkeyboardaction \
		--ontop &
	fi
	disown $!
}

# Open an interactive swiftDialog informing the user that the Platform SSO workflow as failed.
open_dialog_psso_failed() {
	echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
	focus_dialog
	log_pseudo "Dialog Open: Platform SSO Failed"
	"${SWIFT_DIALOG_BINARY}" \
	--title "Platform SSO Registration Failed" \
	--message "**Platform SSO registration has failed.**<br><br>Please contact your administrator if this issue persists." \
	--icon caution \
	--overlayicon "${psso_dialog_icon}" \
	--small \
	--position "${DISPLAY_DIALOG_POSITION}" \
	--button1text "OK" \
	--quitkey p \
	--hidedefaultkeyboardaction \
	--ontop &
	disown $!
}

# The full workflow to check Platform SSO status and if required open interfaces and dialogs to register with Platform SSO.
workflow_psso() {
	local workflow_psso_error
	workflow_psso_error="FALSE"
	psso_workflow_smartcard_active="FALSE"
	psso_workflow_main_active="FALSE"
	psso_workflow_user_active="FALSE"
	
	# Initial Platform SSO configuration checks. This sets ${psso_extension_identifier}, ${psso_login_type}, and ${psso_display_name}.
	if [[ -e "${SSO_MANAGED_PLIST}" ]]; then
		psso_extension_identifier=$(/usr/libexec/PlistBuddy -c "Print :ExtensionIdentifier" "${SSO_MANAGED_PLIST}" 2> /dev/null)
		psso_login_type=$(/usr/libexec/PlistBuddy -c "Print :PlatformSSO:AuthenticationMethod" "${SSO_MANAGED_PLIST}" 2> /dev/null)
		psso_display_name=$(/usr/libexec/PlistBuddy -c "Print :PlatformSSO:AccountDisplayName" "${SSO_MANAGED_PLIST}" 2> /dev/null)
	fi
	if [[ -z "${psso_extension_identifier}" ]] || [[ -z "${psso_login_type}" ]] || [[ -z "${psso_display_name}" ]]; then
		log_pseudo "Warning: Could not resolve required Plaftorm SSO attributes from the managed preference located at ${SSO_MANAGED_PLIST}:\n$(/usr/libexec/PlistBuddy -c "Print :" "${SSO_MANAGED_PLIST}" 2> /dev/null)"
		log_pseudo "Status: Attempting failover configuration validation via app-sso command..."
		killall "AppSSOAgent" > /dev/null 2>&1
		sleep 1
		local app_sso_response
		app_sso_response=$(app-sso platform -s)
		[[ -z "${psso_extension_identifier}" ]] && psso_extension_identifier=$(echo "${app_sso_response}" | sed -e '1,/Device Configuration:/d' | jq -r '.extensionIdentifier' 2> /dev/null)
		[[ -z "${psso_login_type}" ]] && psso_login_type=$(echo "${app_sso_response}" | sed -e '1,/Device Configuration:/d' | jq -r '.loginType' 2> /dev/null)
		[[ -z "${psso_display_name}" ]] && psso_display_name=$(echo "${app_sso_response}" | sed -e '1,/Device Configuration:/d' | jq -r '.accountDisplayName' 2> /dev/null)
	fi
	if [[ -z "${psso_extension_identifier}" ]] || [[ -z "${psso_login_type}" ]] || [[ -z "${psso_display_name}" ]]; then
		log_pseudo "Warning: Could not resolve required Plaftorm SSO attributes from the app-sso command results:\n${app_sso_response}"
		[[ -z "${psso_extension_identifier}" ]] && log_pseudo "Error: Could not determine Platform SSO extension identifier. This is a required value for Platform SSO." && workflow_psso_error="TRUE"
		[[ -z "${psso_login_type}" ]] && log_pseudo "Error: Could not determine Platform SSO login type. This is a required value for Platform SSO." && workflow_psso_error="TRUE"
		[[ -z "${psso_display_name}" ]] && log_pseudo "Error: Could not determine Platform SSO account display name. This is a required value for the pseudo workflow." && workflow_psso_error="TRUE"
	fi
	
	# Platform SSO extension application checks. This sets ${psso_dialog_idp_string}, ${psso_login_type_string}, and ${psso_dialog_icon}.
	if [[ "${psso_extension_identifier}" == "com.microsoft.CompanyPortalMac.ssoextension" ]]; then
		if [[ -e "/Applications/Company Portal.app" ]]; then
			psso_dialog_idp_string="Entra ID"
			psso_dialog_icon="/Applications/Company Portal.app/Contents/Resources/AppIcon.icns"
		else
			log_pseudo "Error: The required Platform SSO software Company Portal.app is not installed." && workflow_psso_error="TRUE"
		fi
	fi
	if [[ "${psso_extension_identifier}" == "com.okta.mobile.auth-service-extension" ]]; then
		if [[ -e "/Applications/Okta Verify.app" ]]; then
			psso_dialog_idp_string="Okta"
			psso_dialog_icon="/Applications/Okta Verify.app/Contents/Resources/AppIcon.icns"
			check_current_user_default_browser
			[[ -z "${current_user_default_browser}" ]] && workflow_psso_error="TRUE"
		else
			log_pseudo "Error: The required Platform SSO software Okta Verify.app is not installed." && workflow_psso_error="TRUE"
		fi
	fi
	if [[ "${workflow_psso_error}" == "FALSE" ]]; then
		[[ $(echo "${psso_login_type}" | grep -c 'SecureEnclave') -gt 0 ]] && psso_login_type_string="Secure Enclave"
		[[ $(echo "${psso_login_type}" | grep -c 'SmartCard') -gt 0 ]] && psso_login_type_string="PIV/SmartCard"
		[[ $(echo "${psso_login_type}" | grep -c 'Password') -gt 0 ]] && psso_login_type_string="IdP Password"
		log_pseudo "Status: Platform SSO configuration for ${psso_dialog_idp_string} using ${psso_login_type_string} authentication with the display name \"${psso_display_name}\"."
	else
		log_pseudo "Exit: Platform SSO workflow failed due to errors." && exit_error
	fi
	
	# If Platform SSO is already enabled then skip the workflow except for enabling AutoFill extensions.
	check_psso_user_status
	if [[ "${REPAIR_MODE}" != "TRUE" ]] && [[ "${psso_user_status_dscl}" != "FALSE" ]] && [[ "${psso_user_status_login_name}" != "FALSE" ]] && [[ $(echo "${psso_user_status_state}" | grep -c 'Normal') -gt 0 ]]; then
		log_pseudo "Status: Platform SSO is already registered for local user ${current_user_account_name} (${current_user_id}) to account ${psso_user_status_login_name}."
		[[ "${ENABLE_AUTOFILL_EXTENSIONS}" == "TRUE" ]] && enable_psso_autofill_extensions
		[[ "${UPDATE_JAMF_PRO}" == "TRUE" ]] && jamf_pro_update_inventory # This function has no user dialogs.
		return 0
	fi
	
	# Handle the initial Platform SSO Registration dialog.
	local psso_registration_status
	psso_registration_status=$(check_psso_registration_status)
	if [[ "${REPAIR_MODE}" != "TRUE" ]] && { [[ "${psso_registration_status}" == "FALSE" ]] || [[ "${psso_registration_status}" == "CLOSE" ]]; }; then
		log_pseudo "Status: Informing user that Platform SSO is required and will be configured for local user ${current_user_account_name} (${current_user_id})."
		open_dialog_psso_required
		if [[ "${dialog_psso_required_result}" -eq 4 ]]; then
			log_pseudo "Error: The initial Platform SSO workflow dialog timed out after ${TIMEOUT_DIALOG_SECONDS} seconds." && workflow_psso_error="TRUE"
		elif [[ "${dialog_psso_required_result}" -gt 0 ]]; then
			log_pseudo "Error: The initial Platform SSO workflow dialog returned unexpected result: ${dialog_psso_required_result}" && workflow_psso_error="TRUE"
		fi
	fi
	
	# If the authentication workflow requires a SmartCard then make sure the user has their SmartCard attached.
	if [[ "${workflow_psso_error}" == "FALSE" ]] && [[ $(echo "${psso_login_type}" | grep -c 'SmartCard') -gt 0 ]]; then
		if [[ $(security list-smartcards 2>&1 | grep -c "No smartcards found.") -gt 0 ]]; then
			log_pseudo "Status: Starting Platform SSO registration workflow by waiting for a SmartCard with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
			psso_workflow_smartcard_active="TRUE"
			open_dialog_smartcard_required
			focus_psso_registration
			local psso_smartcard_start_epoch
			psso_smartcard_start_epoch=$(date +%s)
			while [[ $(security list-smartcards 2>&1 | grep -c "No smartcards found.") -gt 0 ]]; do
				if [[ $(( psso_smartcard_start_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
					log_pseudo "Error: Waiting for a SmartCard timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_psso_error="TRUE"
					break
				fi
				focus_psso_registration
				sleep 1
			done
		fi
		smartcard_array=($(security list-smartcards 2> /dev/null))
		if [[ -n "${smartcard_array[*]}" ]]; then
			[[ "${psso_workflow_smartcard_active}" == "FALSE" ]] && log_pseudo "Status: A SmartCard is already attached."
			[[ "${psso_workflow_smartcard_active}" == "TRUE" ]] && log_pseudo "Status: A SmartCard is now attached. Waiting for a SmartCard took $(( $(date +%s) - psso_smartcard_start_epoch )) seconds to complete."
		else
			log_pseudo "Error: Unable to acquire SmartCard listing." && workflow_psso_error="TRUE"
		fi
	fi
	
	# At this point it's time to open Platform SSO registration.
	if [[ "${workflow_psso_error}" == "FALSE" ]]; then
		[[ "${psso_workflow_smartcard_active}" == "FALSE" ]] && log_pseudo "Status: Starting Platform SSO registration workflow with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
		[[ "${psso_workflow_smartcard_active}" == "TRUE" ]] && log_pseudo "Status: Continuing Platform SSO registration workflow with a ${TIMEOUT_WORKFLOW_SECONDS} second timeout..."
		[[ -n "${current_user_default_browser}" ]] && do_not_hide_bundle_id="${current_user_default_browser}"
		psso_workflow_main_active="TRUE"
		local psso_registration_status
		local psso_workflow_start_epoch
		psso_workflow_start_epoch=$(date +%s)
		[[ "${ENABLE_AUTOFILL_EXTENSIONS}" == "TRUE" ]] && enable_psso_autofill_extensions
		log_pseudo "Status: Attempting to open Platform SSO registration..."
		[[ $(open_psso_registration) == "FALSE" ]] && log_pseudo "Error: Opening Platform SSO registration timed out after ${TIMEOUT_OPEN_SECONDS} seconds." && workflow_psso_error="TRUE"
		[[ "${workflow_psso_error}" == "FALSE" ]] && open_dialog_psso_start
		while [[ "${workflow_psso_error}" == "FALSE" ]] && { [[ "${REPAIR_MODE}" == "TRUE" ]] || [[ "${psso_user_status_dscl}" == "FALSE" ]] || [[ "${psso_user_status_login_name}" == "FALSE" ]]; }; do
			if [[ $(( psso_workflow_start_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
				log_pseudo "Error: Platform SSO registration workflow timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_psso_error="TRUE"
				break
			fi
			[[ -z "${do_not_hide_bundle_id}" ]] && focus_psso_registration
			psso_registration_status=$(check_psso_registration_status)
			if [[ "${psso_registration_status}" == "ACTIVE" ]] && [[ "${psso_workflow_user_active}" == "FALSE" ]]; then
				log_pseudo "Status: Platform SSO registration is open and the user is actively registering."
				open_dialog_psso_active
				psso_workflow_user_active="TRUE"
			elif [[ "${psso_registration_status}" == "AUTOFILL" ]]; then
				break
			elif [[ "${psso_registration_status}" == "FALSE" ]]; then
				log_pseudo "Status: Attempting to re-open Platform SSO registration (the user likely closed the registration window)..."
				[[ $(open_psso_registration) == "FALSE" ]] && log_pseudo "Error: Opening Platform SSO registration timed out after ${TIMEOUT_OPEN_SECONDS} seconds." && workflow_psso_error="TRUE"
				[[ "${workflow_psso_error}" == "TRUE" ]] && break
			elif [[ "${psso_registration_status}" == "CLOSE" ]]; then
				check_psso_user_status
				{ [[ "${psso_user_status_dscl}" == "FALSE" ]] || [[ "${psso_user_status_login_name}" == "FALSE" ]]; } && log_pseudo "Error: Detected Platform SSO registration interface failure." && workflow_psso_error="TRUE"
				break
			fi
			sleep 1
			check_psso_user_status
		done
		[[ -n "${do_not_hide_bundle_id}" ]] && unset do_not_hide_bundle_id
	fi
	
	# At this point the user is technically registered for SSO but may need to complete other tasks.
	if [[ "${workflow_psso_error}" == "FALSE" ]] && [[ "${psso_workflow_user_active}" == "TRUE" ]]; then
		local psso_workflow_end_epoch
		psso_registration_status=$(check_psso_registration_status)
		if [[ "${ENABLE_AUTOFILL_EXTENSIONS}" == "TRUE" ]] && [[ "${psso_registration_status}" == "AUTOFILL" ]]; then
			log_pseudo "Status: Closing Platform SSO registration AutoFill window..."
			close_psso_registration_autofill
			psso_registration_status=$(check_psso_registration_status)
		fi
		if [[ $(echo "${psso_login_type}" | grep -c 'Password') -gt 0 ]] && [[ "${psso_registration_status}" == "ACTIVE" ]]; then
			log_pseudo "Status: Waiting for IdP password sync to local user account..."
			open_dialog_password_sync
			psso_workflow_end_epoch=$(date +%s)
			while [[ "${psso_registration_status}" != "CLOSE" ]]; do
				if [[ $(( psso_workflow_end_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
					log_pseudo "Error: IdP password sync timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_psso_error="TRUE"
					break
				fi
				focus_psso_registration
				sleep 1
				psso_registration_status=$(check_psso_registration_status)
			done
			[[ "${workflow_psso_error}" == "FALSE" ]] && log_pseudo "Status: IdP password sync took $(( $(date +%s) - psso_workflow_end_epoch )) seconds to complete."
		fi
		if [[ $(echo "${psso_login_type}" | grep -c 'SmartCard') -gt 0 ]] && [[ "$(check_psso_smartcard_auth_status)" == "TRUE" ]]; then
			log_pseudo "Status: Waiting for SmartCard paring to local user account..."
			open_dialog_smartcard_pairing
			psso_workflow_end_epoch=$(date +%s)
			while [[ "$(check_psso_smartcard_auth_status)" == "TRUE" ]] || [[ "${psso_registration_status}" != "CLOSE" ]]; do
				if [[ $(( psso_workflow_end_epoch + TIMEOUT_WORKFLOW_SECONDS )) -lt $(date +%s) ]]; then
					log_pseudo "Error: SmartCard paring timed out after ${TIMEOUT_WORKFLOW_SECONDS} seconds." && workflow_psso_error="TRUE"
					break
				fi
				focus_psso_registration
				sleep 1
				psso_registration_status=$(check_psso_registration_status)
			done
			[[ "${workflow_psso_error}" == "FALSE" ]] && log_pseudo "Status: SmartCard paring took $(( $(date +%s) - psso_workflow_end_epoch )) seconds to complete."
		fi
	fi
	
	# Handle any PSSO workflow errors and exit.
	if [[ "${workflow_psso_error}" == "FALSE" ]]; then
		log_pseudo "Status: Platform SSO is now registered for local user ${current_user_account_name} (${current_user_id}) to account ${psso_user_status_login_name}. The Platform SSO workflow took $(( $(date +%s) - psso_workflow_start_epoch )) seconds to complete."
		close_psso_registration
		echo "quit:" >> "${SWIFT_DIALOG_COMMAND_FILE}" && sleep 0.1
		if [[ "${UPDATE_JAMF_PRO}" == "TRUE" ]]; then
			jamf_pro_update_inventory
		elif [[ "${UPDATE_WORKSPACE_ONE}" == "TRUE" ]]; then
			workspace_one_update_inventory
			open_dialog_psso_success & disown
		else
			open_dialog_psso_success & disown
		fi
	else
		killall "AppSSOAgent" > /dev/null 2>&1
		{ [[ "${psso_workflow_smartcard_active}" == "TRUE" ]] || [[ "${psso_workflow_main_active}" == "TRUE" ]]; } && open_dialog_psso_failed & disown
		log_pseudo "Exit: Platform SSO workflow failed due to errors." && exit_error
	fi
}

# MARK: *** Main Workflow ***
################################################################################

main() {
	workflow_startup # This function only completes if the system and user are ready to complete further workflows.
	[[ "${REPAIR_MODE}" != "TRUE" ]] && workflow_touch_id # If Touch ID is available and required then this function only completes if the user has enabled Touch ID.
	workflow_psso # This function only completes if the user has successfully registred with Platform SSO.
	[[ "${update_inventory_error}" == "TRUE" ]] && log_pseudo "Exit: Unable to fully complete the requested inventory update." && exit_error
}

main "$@"
exit_success
